name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_ACCESS }}

      - name: Installing Dependencies
        run: |
          sudo apt install -y libboost-dev
          sudo apt install -y libopenblas-dev liblapack-dev libarpack2-dev libsuperlu-dev
          sudo apt install -y libarmadillo-dev
          sudo apt install -y nlohmann-json3-dev

      - name: Configuring CMake
        run: cmake -S . -B build

      - name: Building Baaraan
        run: cmake --build build --parallel 10