name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_ACCESS }}

      - name: Installing Dependencies
        run: |
          sudo apt-get install -y libboost-dev
          sudo apt-get install -y libboost-test-dev 
          sudo apt-get install -y libopenblas-dev liblapack-dev libarpack2-dev libsuperlu-dev
          sudo apt-get install -y libarmadillo-dev

      - name: Configure
        run: cmake -DENABLE_TESTS=ON -S . -B build/

      - name: Build
        run: cmake --build build/ --parallel 10

      - name: Test
        run: cmake --build build/ --target test